#!/usr/bin/env bash

###############################################################################
#### C O N S T A N T S ########################################################
###############################################################################
####[ spgi install DIR ]####
############################

####[ GitHub  UserName ]####
############################

####[ HackReactor path ]####
############################
###############################################################################

while getopts "h:p:t" optionName; do
  case "$optionName" in
    h) print_help;;
    p) print_help p;;
    t) print_help t;;
  esac
done

if [ "$1" = "p" ] || [ "$1" = "pr" ] || [ "$1" = "pull" ]; then
  hack_repo="${PWD##*/}"
  gh pr create -R "hackreactor/${hack_repo}" -B "${mine_gitu}"
  exit 0
fi
if [ "$1" = "t" ] || [ "$1" = "tp" ] || [ "$1" = "toy" ]; then
  cd "$hack_path"
  hack_repo='hr-rfe2-toy-problems'
  printf '%s\n' "update your local copy of the toy problem repo?"
  printf '%s\n' "this will checkout your master branch"
  printf '%s\n' "and pull upstream master from HR"
  read -r -p "OK? (y/n)" response
  if [ "${response}" != "n" ]; then
    cd $hack_repo
    git remote add upstream "https://github.com/hackreactor/$hack_repo"
    git checkout master
    git pull --no-edit upstream master
    cd "$hack_repo"
    cd "$(ls -t | head -n 1)"
    # nvim *.js
    printf '%s\n' "dropping you off at: $PWD"
    $SHELL
    exit 0
  fi
fi

#
yes_no() {
  printf '%s\n%s\n%s\n' "press <Enter> to accept default" \
                        "     Y: $1"                      \
                        "     n: $2"
  read -r -p "[Y/n]?: " response
  if [ "$response" = "n" ] || [ "$response" = "N" ]; then
    return 1
  else
    return 0
  fi
}

repo_list_sorted=$(gh repo list hackreactor --private --no-archived |\
            awk '/hr-rfe/ {print $3, substr($1,13)}' | sort -r)
# this is way too much piping, should be able to do everything with awk?
repo_latest=$(echo "$repo_list_sorted" | sed -n '1p' | awk '{print $2}')
printf '\n%s\n\n' "latest repo: $repo_latest"
yes_no "this is the repo I want" "give me a bigger list"
if [ "$?" -eq 1 ]; then
  repo_list=$(gh repo list hackreactor --private --no-archived |\
              awk -v ORS=" " '/hr-rfe/ {print substr($1,13)}')
  PS3="select HR repo: "
  select hack_repo in $repo_list; do
    case $hack_repo in
      *) printf '\n%s\n' "selected repo: ${hack_repo}"
         break;;
    esac
  done
else
  hack_repo="${repo_latest}"
fi
#repo_list=$(gh repo list hackreactor --private |\
#            awk -v ORS=" " '/hr-rfe/ {print $1}')
#repo_listed=$($repo_list | awk -v ORS=" " '/hr-rfe/ {print $1}')
#latest_repo="$($repo_list | awk '/hr-rfe/ {print $3, $1}' |\
#               sort -r | sed -n '1p')"
#echo $latest_repo
#exit 0
#PS3="select hackreactor repo: "
#select hack_repo in $repo_list; do
#  break
#done
printf '\n%s\n' "selected repo: $hack_repo"

cd "$hack_path"

if [ -d ./$hack_repo ]; then
  if [ "$hack_repo" = "hr-rfe2-toy-problems" ]; then
      printf '%s\n' "update your local copy of the toy problem repo?"
      printf '%s\n' "this will checkout your master branch"
      printf '%s\n' "and pull upstream master from HR"
      read -r -p "OK? (y/n)" response
      if [ "${response}" != "n" ]; then
        cd $hack_repo
        git remote add upstream "https://github.com/hackreactor/$hack_repo"
        git checkout master
        git pull --no-edit upstream master
        cd "$hack_repo"
        printf '%s\n' "dropping you off at: $PWD"
        $SHELL
        exit 0
      fi
  else
    printf '%s\n' "dir exists!!!"
    exit 0
  # ask to overwrite?
  fi
else
  gh repo fork "hackreactor/$hack_repo"
  cd "$hack_repo"
  $SHELL
  exit 0
fi
